
trained_model : /content/drive/MyDrive/pretrainedmodels/craft_mlt_25k.pth
iam_dataset_path: /content/drive/MyDrive/pretrainedmodels/iamdatasetmodel.pth
text_threshold : 0.7
low_text : 0.4
link_threshold : 0.4
cuda : False
canvas_size : 1280
mag_ratio : 1.5
epochs : 5
pretrained : True
poly : False
show_time : False
test_folder : /content/drive/MyDrive/datasets/predict_images/raw_images/
report_folder : /content/drive/MyDrive/datasets/predict_images/raw_images/reports/
data_limit : 10
refine : False
dataset : /content/drive/MyDrive/datasets/predict_images/raw_images/reports/dataset.csv
wordspath : /content/drive/MyDrive/datasets/predict_images/raw_images/words/
weigtht_path :  /content/drive/MyDrive/pretrainedmodels/
train_data_path : /content/drive/MyDrive/datasets/
project_path : ./
crop_words : False
