
trained_model : pretrainedmodels/craft_mlt_25k.pth
iam_dataset_path: pretrainedmodels/craft_mlt_25k.pth
text_threshold : 0.7
low_text : 0.4
link_threshold : 0.4
cuda : False
canvas_size : 1280
mag_ratio : 1.5
epochs : 5
pretrained : True
poly : False
show_time : False
test_folder : datasets/predict_images/raw_images/
report_folder : datasets/predict_images/raw_images/reports/
data_limit : 10
refine : False
dataset : datasets/predict_images/raw_images/reports/dataset.csv
wordspath : datasets/predict_images/raw_images/words/
weigtht_path :  pretrainedmodels/
train_data_path : datasets/
project_path : ./
crop_words : False
