pretrainedmodels : /content/drive/MyDrive/pretrainedmodels/
train_images: /content/drive/MyDrive/datasets/train_images/
predict_images: /content/drive/MyDrive/datasets/predict_images/
predict_words_path : raw_images/words/
test_folder : raw_images/
report_folder : raw_images/reports/
refine : False
dataset : /content/drive/MyDrive/datasets/predict_images/raw_images/reports/dataset.csv
project_path : ./
crop_words : True
untar_iamdataset: False
#parameters for CRAFT Model
text_threshold : 0.7
low_text : 0.4
link_threshold : 0.4
cuda : False
canvas_size : 1280
mag_ratio : 1.5
epochs : 10
pretrained : True
poly : False
show_time : False
data_limit : 10
pretrained_OPT: 1


